apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-platform-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: pod-alerts
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} po crash-on ne namespace {{ $labels.namespace }}"

        - alert: PodNotReady
          expr: kube_pod_status_ready{condition="false", namespace!="default"} == 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} nuk eshte Ready prej 2 minutash"

    - name: resource-alerts
      rules:
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "CPU usage eshte mbi 80% ne {{ $labels.instance }}"

        - alert: HighMemoryUsage
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Memory usage eshte mbi 85% ne {{ $labels.instance }}"
