apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/monitoring
    repoURL: git@github.com:shalaermal/devops-platform-ai.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true