replicaCount: 3

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

# Activate HPA - auto scaling
hpa:
  enabled: true
  maxReplicas: 4
  cpu: 50

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: podinfo.local
      paths:
        - path: /
          pathType: Prefix