apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
