apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/rbac
    repoURL: git@github.com:shalaermal/devops-platform.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
