apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/argocd
    repoURL: git@github.com:shalaermal/devops-platform-ai.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true